apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  POSTGRESQL_POSTGRES_PASSWORD: YWRtaW4=                # admin en base64
  POSTGRESQL_USERNAME: YWRtaW4=                         # admin en base64
  POSTGRESQL_PASSWORD: YWRtaW4=                         # admin en base64
  POSTGRESQL_REPLICATION_USER: cmVwbF91c2Vy             # repl_user en base64
  POSTGRESQL_REPLICATION_PASSWORD: cmVwbF9wYXNzd29yZA== # repl_password en base64
  DATABASE_URL: cG9zdGdyZXNxbDovL2FkbWluOmFkbWluQGRhdGFiYXNlLTAucG9zdGdyZXM6NTQzMi9hcHA=  # postgresql://admin:admin@database-0.postgres:5432/app en base64